### ISSUE TITLE
density plot to blurred if amplitude is small

### ISSUE THREAD

**Issue by chris3110** [jniediek/combinato#1]
If the mean amplitude of a cluster is small, i.e. 15 muV, the linespace for the density plot uses, as implemented right now, 2_max_of_mean as # of points. This would lead to 30 points for the example. It is better to implement it in a way that for example at least 150 points are used (as before the change to fit everything to the max_of_means).
this means: 
bins_density = np.linspace(-2_max_of_means,
                                   2_max_of_means,
                                   max(150,2_max_of_means))
instead of:
bins_density = np.linspace(-2_max_of_means,
                                   2_max_of_means,
                                   2*max_of_means)

**Comment by jniediek** [comment]
Has been implemented at some point some time ago.
