### ISSUE TITLE
ubuntu installation issue:

### ISSUE THREAD

**Issue by dta0115** [jniediek/combinato#28]
following output is shown when running "python tools/test_installation.py"
[[
Unable to load Combinato: No module named combinato.default_options
Check your PYTHONPATH and make sure to copy
combinato/default_options.py to combinato/options.py
Re-run after fixing problems.
Found display
Found 'montage', plotting continuous data possible.
]]

**Comment by jniediek** [comment]
Did you run python setup_options.py?
