### ISSUE TITLE
Sampling rate for old Ncs files 

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#29]
Hi, 

I am experiencing a very peculiar issue. While trying to use Combinato to sort older .ncs data (~2005), my spike times are shifted forward with respect to the spike times detected by WaveClus. This was seen by comparing the smallest and biggest spiketimes between the Combinato and WaveClus results, with the largest Combinato spike times extending beyond the actual length of the recording. 

They are not shifted forward by a consistent amount of time between recordings, but it is on the magnitude of ~1-2 minutes usually. **This has not been an issue with more recent .Ncs files, circa 2014-2015**.

**Comment by jniediek** [comment]
Hi,

I would like to investigate this further. Would it be possible to upload one of the old Ncs files to some place for me to check? You can send me any login details via email to jonied@posteo.de.

**Comment by seqasim** [comment]
Yes, I sent you a link to a google drive with one old Ncs file and one new Ncs file, both of which should have units.

**Comment by jniediek** [comment]
Hi,
which version of `wave_clus` do you use? The old Ncs file you sent has a 27777 Hz as sampling rate in its header, while the actual time difference between two subsequent sampling points is 36 µs (which  corresponds to 27777.77.... Hz). As far as I can see, new versions of `wave_clus` use the actual time difference, not the sampling rate from the header, but I don't know about old versions of `wave_clus`. Or did you maybe pass 27777 as hardcoded sampling rate?

I attach here a plot of filtered data from a channel recorded with these settings, and time points of extracted spikes *from Combinato*, to show that the extraction works correctly.

![spike_sample](https://user-images.githubusercontent.com/3511716/29315663-a4a61bce-81c4-11e7-8a0e-a4afa7177e8c.png)

For the sake of completeness, here is the code used to generate the plot after spike extraction:
```

# -*- coding: utf-8 -*-
from __future__ import division
import numpy as np
import tables
import matplotlib.pyplot as mpl
from combinato import NcsFile, DefaultFilter
from combinato.basics.nlxio import time_upsample

n_samples = 20000

ncs_fname = 'somename.Ncs'
spike_fname = 'somename/data_somename.h5'

ncs_fid = NcsFile(ncs_fname)
num_rec = ncs_fid.num_recs

data, ts = ncs_fid.read(num_rec - 1000, num_rec, 'both')

data = data * (1e6 * ncs_fid.header['ADBitVolts'])

my_filter = DefaultFilter(ncs_fid.timestep)

data_filt = my_filter.filter_detect(data)

uptime = time_upsample(ts, ncs_fid.timestep)/1000

spike_fid = tables.open_file(spike_fname, 'r')
spiketimes = spike_fid.root.pos.times[:]
spike_fid.close()

figure = mpl.figure(figsize=(9, 3))
plot = figure.add_axes([.1, .2, .8, .7])

plot.plot(uptime[:n_samples], data_filt[:n_samples])

idx = (spiketimes >= uptime[0]) & (spiketimes <= uptime[n_samples])

plot.plot(spiketimes[idx], np.ones(idx.sum()), ls='none', marker='|', ms=20, mew=1.5)
plot.set_ylabel(u'µV')
plot.set_xlabel('ms')

mpl.show()
```

**Comment by seqasim** [comment]
Hey,

This was very very helpful! 

I found the problem. The spiketimes given by Combinato are indeed shifted forward in time from the spiketimes given by this old version of Waveclus (data was clustered back in 2007, I think). Since the exact spikes from both methods are different, I can only estimate that this is the precise shift, but it captures the consistent offset I am seeing:
 
`
from __future__ import division
import numpy as np
import tables
import matplotlib.pyplot as mpl
from combinato import NcsFile, DefaultFilter
from combinato.basics.nlxio import time_upsample

n_samples = 20000

ncs_fname = 'somename.Ncs'
spike_fname = 'somename/data_somename.h5'

ncs_fid = NcsFile(ncs_fname)

data, ts = ncs_fid.read(start=0, stop=None, 'both')
shift = ts/1000
`

I do not know exactly how to interpret this, but it is consistent across at least 3 different sessions of these old recordings.

**Comment by jniediek** [comment]
I'm happy to hear that my comment was useful. Is the problem now solved for you, or is there anything mysterious left?

**Comment by seqasim** [comment]
The problem is solved! Thanks for the help!
