### ISSUE TITLE
Python/multiprocessing in windows

### ISSUE THREAD

**Issue by ferchaure** [jniediek/combinato#30]
Hi! I was trying combinato in wWindows, and I got this error
> File "C:\ProgramData\Miniconda3\envs\combinato\lib\multiprocessing\forking.py", line 504, in prepare
> ImportError    : file, path_name, etc = imp.find_module(main_name, dirs)
> ImportError No module named css-extractfile, path_name, etc = imp.find_module(main_name, dirs):
> ImportError: No module named css-extract
> No module named css-extract

I found something similar [here](https://github.com/python-diamond/Diamond/issues/187), changed the name of the file  css-extract to  css-extract.py and it works. Just to tell you, If someone gets the same issue

**Comment by jniediek** [comment]
Thanks a lot. This question had indeed been asked a few times before!
