### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by ferchaure** [jniediek/combinato#31]
Hi I'm getting
"TypeError: The numpy boolean negative, the `-` operator, is not supported, use t he `~` operator or the logical_not function instead." I'm sure why, maybe because I'm using newest numpy
For now I saw this issue in:
-the function template_match, inside combinato/cluster/dist.py 
- main() in combinato/cluster/create_groups.py

**Comment by jniediek** [comment]
Thanks for reporting, I'm looking into it.
