### ISSUE TITLE
Stalling during css-cluster

### ISSUE THREAD

**Issue by pkantak** [jniediek/combinato#34]
Hi!

I am using your combinato package to cluster some stereo-EEG data and have been running into a peculiar problem which I thought you may be able to shed some light on.
 
I am using the attached code to automate the extraction/clustering procedure (using .mat files I created from Blackrock micro EEG recording output files).  It seems “css-extract” and “css-mask-artifacts” works fine, however when the code enters “css-cluster” it seems to stall at the clustering data step.  I’ve run it overnight on my local machine and it still seems to stall on that step.  However, if I process manually using “css-simple-clustering” it seems to work okay.  Would you be able to provide any guidance on why this would be the case? I’ve attached a screenshot of my terminal window as well.
 
Any help you can provide would be greatly appreciated!

`#!/bin/bash

declare -a arr=("/Users/Pranish/Desktop/Subj_File_Test/UT084_ex" "/Users/Pranish/Desktop/Subj_File_Test/UT086_ex" "/Users/Pranish/Desktop/Subj_File_Test/UT105_ex")

mkdir /Users/Pranish/Desktop/Subj_File_Test/Combinato_Clustering/$(date '+%d-%b-%Y')

cd /Users/Pranish/Desktop/Subj_File_Test/Combinato_Clustering/$(date '+%d-%b-%Y')

touch do_manual_neg.txt

for file in "${arr[@]}"; do

    cd $file

    for chan in NS6_00[1-8].mat; do

        css-extract --matfile ${chan%%.*}.mat

        css-mask-artifacts

        h5_file="data_${chan%%.*}.h5"

        path=${chan%%.*}/"data_${chan%%.*}.h5"

        cd ${chan%%.*}

        css-prepare-sorting --neg --datafile "$h5_file"

        css-cluster --jobs sort_neg_pra.txt

        css-combine --jobs sort_neg_pra.txt

        cd /Users/Pranish/Desktop/Subj_File_Test/Combinato_Clustering/$(date '+%d-%b-%Y')

        echo "$file$path" >> do_manual_neg.txt

        cd $file

    done
     
done`

![image](https://user-images.githubusercontent.com/41026437/42477168-c5378d40-8395-11e8-92ef-31faef2d71c5.png)

**Comment by jniediek** [comment]
Hi @pkantak,
clustering your ~10000 spikes should take less than one minute. There is definitively something wrong, but since there is no error message at all, I have no clue what the problem might be. Would you mind uploading the file `data_NS6_001.h5` to some server for me check what's wrong?

**Comment by pkantak** [comment]
Hi @jniediek! Thanks for getting back to me.

You can find my entire combinato directory at this link: 
https://drive.google.com/open?id=1AMSqVvbWSoagomzrGHmg0x_KRAKawEhI

The data_NS6_001.h5 file is also in this folder.

I've uploaded my combinato directory as well as the data_NS6_001.h5 file because I also ran the css-cluster as a stand-alone command with the simulation_5 data that was provided in the tutorial and got the same result (stall at the clustering stage).  Css-simple-clustering worked fine for the simulation data as well.

Thank you very much for taking the time to look into this!

-Pranish

**Comment by jniediek** [comment]
![sorted_unknown_ns6_001_pos_sort_pos_joh](https://user-images.githubusercontent.com/3511716/42632731-da115b3a-85e6-11e8-92e6-dcd2d7482cb5.png)

![sorted_unknown_ns6_001_neg_sort_neg_joh](https://user-images.githubusercontent.com/3511716/42632966-ac68e5d0-85e7-11e8-90c4-17b7c3d43a7d.png)

These results appeared after less than 2 minutes on my machine, and I used your bash script. So the problem is more sophisticated than a simple bug or data error. 

A general remark, which might also resolve the problem: one of the features of combinato is that it uses multiprocessing across channels. So in your situation it would make sense to first extract the spikes in a loop over channels, and then run `css-mask-artifacts` *only once* (it runs on all channels every time you run it!) and then:

    ls *.h5 > do_sort.txt
    css-prepare-sorting --jobs do_sort.txt
    css-cluster --jobs   and so on

You can even do `ls */*.h5 > do_sort.txt`, to run across different folders, all the scripts are subdirectory-aware.

Also make sure to delete the sort_pos_abc.txt and sort_neg_abc.txt after each completed action, because jobs are *appended* not replaced. So if you don't delete them, you end up with longer and longer job files!



I hope this helps!

**Comment by pkantak** [comment]
Hi @jniediek ,

Thanks for getting back to me.  I had that suspicion that it was probably an issue with the install of combinato or of some of the slight changes I made.  I'll have to do some troubleshooting this weekend and implement the changes you suggested and see if that resolves the issue.

I''ll let you know soon!

Thanks,
Pranish

**Comment by pkantak** [comment]
Hi @jniediek 

Hope you're having a good week.  So I've tried your suggestions, and seem to be running into a similar problem...even if I just run "css-cluster" as a stand alone command on the simulation_5 data that is provided in the tutorial.

Could this perhaps have something to do with the installation? The steps I took are below:

1) Created an environment for combinato
2) Activated the environment
3) Installed the correct PYQT (4)
4) Navigated to the combinato repository and ran setup_options.py
5) Whenever I use combinato I run "source activate combinato" before using the package

Could something need to be modified in the envs? Do I need to install combinato into the site packages of this envs?

I am quite perplexed, because it seems like most of the other commands work fine when run in succession.  For example, css-simple-clustering works just as it should.

Thanks for all the troubleshooting help!

Pranish

**Comment by pkantak** [comment]
Hi @jniediek ,

That's great to hear, thank you! I apologize if this was not the right way of going about installing combinato, but I had to downgrade PYQT 5 to PYQT 4, and I wasn't sure what it was used for, so I made the separate env.

I used `conda` to create it!

Pranish

**Comment by pkantak** [comment]
Hi @jniediek ,

Hope you're doing well.  Was just wondering if you had had any luck with the debugging? This has still been an issue for us in the lab.

Thank you!

Pranish

**Comment by jniediek** [comment]
Hi @pkantak,
this is just a notice that I haven't forgotten the issue. I just don't have enough time at the moment. This will change.

**Comment by pkantak** [comment]
Hi @jniediek 

No worries! Thanks for keeping it on your radar.

Let me know if you need anything from me!

Pranish
