### ISSUE TITLE
Css-gui: Not seeing sorted data

### ISSUE THREAD

**Issue by oashmaig** [jniediek/combinato#38]
There are no errors outputed into the terminal when I extract data from either a neuralynx or matlab file nor when I run the simple clustering command. I have gotten it to work with the tutorial's matlab simulation file and with the example ncs file. However, when I run css-gui on my data, I do not see any sorted data files under File --> Open. When I look at the file timestamps, I see that combinato created several folders after running the clustering, but the data.h5 file doesn't update after the initial data extraction. I've made sure that I am running css-gui in the correct directory. When I run css-plot-rawsignal and specify the specific h5 data file, it says that plotting took 0 seconds, but with the shorter example ncs file in the tutorial, it says plotting took 3 seconds. Also, when I run the clustering command, it is creating figures with the sorted spikes into the overview folder. I'm using python2.7. Any help would be greatly appreciated.
[combinato.docx](https://github.com/jniediek/combinato/files/3665671/combinato.docx)

**Comment by jniediek** [comment]
A possible reason is that your filenames might not match the pattern in

`combinato/combinato/options.py`:

    # Folder names the GUI should include
    'folder_patterns': ('CSC*', 'test', 'L??', 'u*',
                        'R??', 'L???', 'R???', 'L????', 'R????',
                        'simulation_*', 'spike*'),

**Comment by oashmaig** [comment]
Yes, that was the issue, I'm able to see my sorted data in the css-gui now, thank you so much!
