### ISSUE TITLE
Using Combinato with hdf5 files **EDIT** actually an issue with size

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#42]
Hey, 

I have recently started splitting our BlackRock data into hdf5 files. I tried to extract spikes from this data, and I keep stalling after the first job, on any file I try. The process does not proceed past the point below:

```
css-extract --files 20170224-145604-001_chan107.hdf5 --h5
5
Shortening maxima list from 44 to 44
2
Shortening maxima list from 30 to 30
3
Shortening maxima list from 82 to 82
Job name: 20170224-145604-001_chan107 pending jobs: dict_keys([0]) jnow: 0
Initialized 20170224-145604-001_chan107/data_20170224-145604-001_chan107.h5
saving 20170224-145604-001_chan107, count 0
4
Shortening maxima list from 65 to 65
Work exited
Job name: 20170224-145604-001_chan107 pending jobs: dict_keys([1]) jnow: 1
saving 20170224-145604-001_chan107, count 1
```

If I interrupt, it seems to be stalled here: 

```
Process Process-6:
Process Process-4:
Traceback (most recent call last):
Process Process-5:
  File "/home1/salman.qasim/combinato/css-extract", line 5, in <module>
Process Process-2:
    main()
  File "/home1/salman.qasim/combinato/combinato/extract/extract.py", line 99, in main
    mp_extract(jobs, nWorkers)
  File "/home1/salman.qasim/combinato/combinato/extract/mp_extract.py", line 175, in mp_extract
    p.join()
  File "/home1/salman.qasim/miniconda3/envs/spikeinterface/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home1/salman.qasim/miniconda3/envs/spikeinterface/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home1/salman.qasim/miniconda3/envs/spikeinterface/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

```

**Comment by jniediek** [comment]
Hi,
unfortunately sometimes the `multiprocessing` hides the relevant error messages. A way to debug this will be to run the `read`, `work`, and `save` functions in `mp_extract.py` separately. If you upload one of your hdf5 files and send me a link, I'll look into it.

**Comment by seqasim** [comment]
Ok, I've uploaded two channels here: 
https://drive.google.com/drive/folders/1XDJz9hswrPNn_XV1aMzDjimLILz8R2MC?usp=sharing

I was able to run the `read` and `work` functions fine. Everything stalls when I run the following: 

```
    # start the saver process
    p = Process(target=save, args=[q_work, ctarget])
    p.daemon = True
    p.start()
    p.join()

    for p in procs:
        p.join()
```

**Comment by seqasim** [comment]
Hi, 

Actually I am noticing that even running mp_extract with 1 worker does not work... it still seems to hang on save process: 

`Process Process-2:
    main()
  File "/home1/salman.qasim/combinato/combinato/extract/extract.py", line 100, in main
    mp_extract(jobs, 1)
  File "/home1/salman.qasim/combinato/combinato/extract/mp_extract.py", line 175, in mp_extract
    p.join()
`

**Comment by seqasim** [comment]
Hey, I messed around and this works fine if you only use half the data that is in the google drive link that I shared. So it seems like this is an issue with the multiprocessing module, and specifically `p.join()` hanging on large data. 

I tested my code on the simulation data (works fine). I then tested on the hdf5 cut in half (works fine). 

I tested the code on the same data saved as a matfile, but used the whole data length. This stalled. Then I tested the code on the mat data cut in half (works fine). 

Note that I encounter this problem even with `nWorkers=5` and `blocksize = 10000`

**Comment by seqasim** [comment]
Hey, I noticed this is an issue of data size. 

Test 1: 
Run Combinato while using only the first 1/4th of the session data (in the google drive). This works. 

Test 2:
Run Combinato with the full data, in .mat format. This stalls. 

Test 3: 
Run Combinato while using only the first 1/4th of the .mat data. This works. 

So it seems like this is an issue with  `p.join()` getting stuck when the data in the queue is too large. I am not sure how to fix this. For the MATLAB data we are restricted to one worker and the data cannot be split. But for the HDF5 data I am using `nWorkers=5` and `blocksize=10000`.

**Comment by seqasim** [comment]
The following seems to work for the hdf5 case (but not the MATLAB case): 

I increased `nWorkers` from 5 to 20, and also decreased the hardcoded blocksize for hdf5 files in `mp_extract.py`:
`starts = list(range(0, size, 32000*5*60))`
to 
`starts = list(range(0, size, 32000*1*30))`

**Comment by jniediek** [comment]
Thank you for all the tests!

To avoid the MATLAB case for now, I suggest converting the data to hdf5 by MATLAB. This can be done either by using the `matfile` function (https://www.mathworks.com/help/matlab/ref/matlab.io.matfile.html), or with slightly more control over details by
the HDF5 "high level functions" (https://www.mathworks.com/help/matlab/high-level-functions.html)

**Comment by jniediek** [comment]
I worked a little bit on this issue again. I found that the problem is very similar to this one: https://stackoverflow.com/q/59951832/5733694

Basically, `Queue.put` goes into a deadlock when the size of the put data is too large. I'm thinking about a solution now.

**Comment by pkantak** [comment]
Hey @jniediek, just curious, did you figure out a more permanent solution to this? I have some lengthy recordings that are running into the same problem as Salman was.

Thanks,

Pranish

**Comment by jniediek** [comment]
Hi @pkantak,

I haven't found a real solution. At some point I'll get back to this issue. Does it *not* work for you do convert the data to the h5 format (https://github.com/jniediek/combinato/issues/42#issuecomment-684524120)?

**Comment by seqasim** [comment]
I can verify that the multiprocessing issues continue with large datafiles, even after conversion to .hdf5. For example 16 channels @ 115MB each sort fine, but 16 channels @ 215 MB each do not.

Furthermore, the process stalls during the clustering step (rather than extraction):

```
Clustering data in datafile_202013_20201209_001-002_chan98/sort_neg_sal_0000000_0026016/sort_0_01
Calculating distances
Creating classes
Classes updated
Creating matches
Creating artifact_scores```

If I interrupt, it seems to be stalled in combinato/cluster/cluster.py, in the function argument_parser() at line 320:  

```
pool.map(sort_helper, joblist)
```

**Comment by jniediek** [comment]
The stalling in `css-extract` is most likely due to a completely different reason than the stalling in `css-cluster`. 

Could you run the `css-cluster` command with the option `--single`? This switches off the multiprocessing, and generally creates more meaningful error messages.

Thank you for testing!!

**Comment by seqasim** [comment]
Thank you - this seems to work but requires the `--single` flag for both `css-cluster` and `css-combine `

**Comment by jniediek** [comment]
> Thank you - this seems to work but requires the `--single` flag for both `css-cluster` and `css-combine `

So this means that without the `--single` flag you get stalling and with `--single` everything works? In that case it might be a RAM limitation of your machine?
