### ISSUE TITLE
Using Combinato manager convenience class has a string error (suggested fix)

### ISSUE THREAD

**Issue by a-darcher** [jniediek/combinato#43]
Hi Johannes, 

While using the most recent version of Cominato, I ran into an issue with the combinato.manager.Combinato(SortingManagerGrouped) class, specifically with the called manager.get_group_joined() function. In calling the cluster/spike sign, the current implementation doesn't ignore bytes prefix on the string literal. 

I'm not sure how much the whole of manager_cat.py relies on the class initialized variables, so I fixed my clone with a line-by-line edit on the main function I use for reading out sorted Combinato data, below: 

(starts at Line 304)

     def get_group_joined(self, gid, times=True, spikes=True, artifacts=True):
            """
            get one group, all clusters joined
            """
            ret = dict()

            gtype = self.get_group_type(gid)

            if (artifacts is False) and (gtype == TYPE_ART):
                return ret

            idx = self.sorting.get_cluster_index_joined(gid)
            n_clusters = len(self.sorting.get_cluster_ids_by_gid(gid))
            # shorten it
            sel = (idx >= self.start_idx) & (idx <= self.stop_idx)

            if not sel.any():
                return ret

            idx = idx[sel] - self.start_idx
            # idx -= self.start_idx
        
            ### fix edit
            decoded_sign = self.sign.decode('utf-8')
            ####
            shape = self.times[decoded_sign].shape[0]
            if idx[-1] >= shape:
                idx = idx[idx < shape]
                print('Shortened index!')

            ret['type'] = gtype
            ret['n_clusters'] = n_clusters
            if times:
                ret['times'] = self.times[decoded_sign][idx]
            if spikes:
                ret['spikes'] = self.spikes[decoded_sign][idx]

            return ret

**Comment by jniediek** [comment]
Thank you very much! I had fixed this problem in some other places, but apparently I overlooked the code section you now found! I'll push a fixed version ASAP.

**Comment by alexa-hassien** [comment]
I was having the same issue - I used a-darcher's fix in get_group_joined() as well as get_start_stop_index() and set_sign_times_spikes() a little bit earlier in manager_cat.py. Thanks!
