### ISSUE TITLE
Implement Combinato in SpikeInterface

### ISSUE THREAD

**Issue by ferchaure** [jniediek/combinato#45]
Hi Johannes,

I wanted to ask you if you can implement Combinato in the SpikeInterface project (https://github.com/SpikeInterface). Or give me a hand doing it. 

Cool things about the idea:
- It will be super easy to compare Combinato with other algorithms.
- Combinato will be able to work with all the file formats supported by SpikeInterface.

I know that combination is implemented on Python 2 but even sorters on Matlab (like Wave_clus) are implemented on SpikeInterface, therefore I  think we can overcome that limitation.

The implementation has two parts:

 - **Given a spikeInterface recording run Combinato**. This one is just deciding which is the best file format for Combinato and the cli to call it (I guess `css-extract` and then `css-simple-clustering`). [Yes the cli of Combinato helps a lot for this.] I guess that all the parameters can be given just saving a `local_options.py` in the same folder that the data. Examples of the codes to do this for other sorters are [here](https://github.com/SpikeInterface/spikesorters/tree/master/spikesorters).

- **Load the results of Combinato**. Loading the results of Combinato, SpikeInterface needs only the class and sample of each spike, just that. I don't remember how Combinato label the discarded or unsorted spikes
 Examples of the codes to do this for other sorters are [here](https://github.com/SpikeInterface/spikeextractors/tree/master/spikeextractors/extractors).

Please let me know if you can help me with the implementation.

Cheers
Fernando

**Comment by jniediek** [comment]
Hi Fernando,

I absolutely support this idea, thank you for asking!!

Due to the current COVID situation, with two small daughters, I don't have much time at all. Can you name a date after which doing the SpikeInterface integration wouldn't make sense any more? Then I'll try to fix some time for this. I need to check some details before I can coordinate with you how to split the work. Anyways, it's great that you offer help!!

Just FYI: the current versions of Combinato are already in Python 3. Maybe that helps a bit for the SpikeInterface integration.

Cheers
Johannes

**Comment by ferchaure** [comment]
Awesome!

> Can you name a date after which doing the SpikeInterface integration wouldn't make sense any more?

To be honest, I don't know. From a community point of view, I guess that the sense it will only increase with time. 
Maybe @alejoe91 can help with this question


> the current versions of Combinato are already in Python 3

That is amazing, I saw the dead link [here](https://github.com/jniediek/combinato/wiki/Python3-Qt5) and I thought thas was an inactive part of the project.

Will be the output file format the same? The Python 2 code was well documented and I could add support for reading it in spikeinterface. We could figure out how to run Combinato latter.

**Comment by alejoe91** [comment]
Hi @jniediek 

As @ferchaure said, I don't think it we have a deadline. So whenever you have time it will be great to add Combinato as a sorter. Of course we can also help!
For that purpose, it will be better to apck the code into a Python package, but we can discuss about it later.

Cheers
Alessio

**Comment by ferchaure** [comment]
I did a pull request on [spikeextractors](https://github.com/SpikeInterface/spikeextractors/pull/467) to load combinato results. :nerd_face: 
 
I have to learn/test/ask a few more things before finish the code for the spikesorter but I guess this is a good first step.

**Comment by ferchaure** [comment]
Hi guys, with the last commit of combinato the sorter interface I made [here](https://github.com/ferchaure/spikesorters/blob/master/spikesorters/combinato/combinato.py), is working.

It is required to set the path of the combinato code to work, like ironclus, wave_clus, etc. 

**How run_combinato works**
1. Saves the recording in a .h5 file.
2. Creates a .bat/.sh file with a script that runs css-extract (*) and then css-simple-clustering  (with a flag if the user set a particular type of detection sign )

Probably the descriptions of the sorter and parameters can be improved... I just copy-pasted them and added my broken English on top 

@alejoe91 should I make the pull request on spikesorters now and discuss the changes there?

**Comment by alejoe91** [comment]
Sure @ferchaure go ahead and start a draft PR in spikesorters!!! :)

**Comment by ferchaure** [comment]
I'll close this issue, I just read that combinato is included on spikeinterface 0.10.1  :partying_face:

**Comment by alejoe91** [comment]
@jniediek please let us know if there are updates in installations etc, for example if you upload the package to Pypi
