### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by ferchaure** [jniediek/combinato#46]
I'm trying to use Combinato to analyze a long recording a .mat file of ~3.5 GB. When I try to get the spikes using `extract` I got the error: 
`OverflowError: cannot serialize a bytes object larger than 4 GiB`
I tried as well with python 2 and I got:
`OverflowError: cannot serialize a string larger than 2 GiB`. 

I should be doing something wrong. What do you recommend? I could cut the file in smaller parts but It looks like the multiple file support is just for ncs files. Maybe I could sort the parts independently and then use `css-combine`, but I'm not sure about that.

cheers,

**Comment by ferchaure** [comment]
Hi again, I was able to convert the mat file to h5 and then edit the mp_extractor.py to set the sampling rate. After that combinato could extract and cluster the spikes, but I would like your confirmation that these steps are the correct to handle big files.

**Comment by jniediek** [comment]
Hi Fernando, 

Thanks for the useful comment! The entire `.mat` support in Combinato isn't developed as much as the `.ncs` support. Ideally I would rewrite `css-extract` to be more general and accept many file formats, but at the moment I don't have time for that. The most pragmatic way is certainly to convert the `.mat` files to `.h5` as you did. If you have a good script for this conversion, feel free to create a pull request. There are some other conversion scripts already in the `tools` folder.

**Comment by ferchaure** [comment]
>  Ideally I would rewrite css-extract to be more general and accept many file format

Probably, It will be less work to just support spikeinterface, NWB or any of the projects that support multiple file formats. Otherwise can be a mess maintaining the code to support updates in the formats, new standards etc.

> There are some other conversion scripts already in the tools folder.

Thanks, I have been looking at that code, but I want to parse just the signal and add a sampling rate parameter. Nevertheless, I will use that code as a template.

>feel free to create a pull request

I will do it. Now, I'm working on a way to load combinato results on spikeinterface (I will be doing a lot of pull request to them), and then I will annoy you with a lot of questions when I start coding a way to use combinato from spikeinterface.

**Comment by jniediek** [comment]
> Probably, It will be less work to just support spikeinterface, NWB or any of the projects that support multiple file formats. Otherwise can be a mess maintaining the code to support updates in the formats, new standards etc.

Yes of course, that would have been my intention. But it would still require some rewrite.

> and then I will annoy you with a lot of questions when I start coding a way to use combinato from spikeinterface.

I'm looking forward to that!
