### ISSUE TITLE
combinato installation on Windows

### ISSUE THREAD

**Issue by lubavas** [jniediek/combinato#51]
Dear Johannes,

I’m trying to install combinato on Windows and have some problems.

I run the following code
`python setup_options.py`

and get the following results.
`combinato\options.py exists, not doing anything.`

Everything seems to go well at this point.

Then I run 
`python tools/test_installation.py`

and get
`Unable to load Combinato: No module named 'combinato'
Check your PYTHONPATH and make sure to copy
combinato/default_options.py to combinato/options.py
Re-run after fixing problems.
'montage' from ImageMagick not found: [WinError 2] Не удается найти указанный файл
Plotting continuous data will not work`

I added the combinato folder to my PYTHONPATH. I don’t understand what “to copy
combinato/default_options.py to combinato/options.py” means. Could you explain what this expression means?

Could you help me with my question?

Best wishes,
Luba

**Comment by jniediek** [comment]
Hi Luba! 

I can only guess that what you're seeing has to do with the fact that there is a `combinato` folder inside the folder that you download from Github, giving you `.../combinato/combinato` on you local file system. The **inner** folder has to be in the `PYTHONPATH`, this is the module that python needs to load (the outer folder is the repository, the inner folder is the `combinato` module for python).

As to your other question, what I mean by 

> to copy combinato/default_options.py to combinato/options.py

is to take the file `default_options.py` from the inner `combinato` folder and save it in the same folder under the name `options.py`. But it seems that you did this already, so you can ignore anything that relates to this message I think.

Best,
Johannes

**Comment by lubavas** [comment]
Dear Johannes,

Thank you for the reply!

I added the inner `combinato` folder to my PYTHONPATH as well as other subfolers in the combinato repository. To be on the safe side, I also saved file `default_options.py` as `options.py` in the `.../combinato/combinato` folder. Unfortunately, I still get the same error from my terminal. Do you have other guesses how I can improve?

Best wishes,
Luba

**Comment by jniediek** [comment]
Dear Luba,

can you run the following:

```
python3
>>> import sys
>>> sys.path
```

In my case this gives

`['', '/home/johannes/Repositories/combinato', ...]`

Let's try if you see combinato in this path, too!

Best,
Johannes

**Comment by jniediek** [comment]
Can I close this issue?

**Comment by lubavas** [comment]
> 
> 
> Can I close this issue?

Dear Johannes,

Thank you for the reminder! Actually, the problem persists even after I displayed the PYTHONPATH and found the combinato folder in it. I will be able to write the exact PYTHONPATH contents tomorrow.

Do you have any suggestions on what I can try next?

Best wishes,
Luba

**Comment by jniediek** [comment]
Hi Luba,

so what happens if you do the following

```
python3
>>> from combinato import Combinato
````

Does this throw an error?

Best regards,
Johannes

**Comment by lubavas** [comment]
Hi Johannes,

I ran this command. No, it didn't retrieve and error.

Best wishes,
Luba

**Comment by jniediek** [comment]
Hi,

have you also tried `python3 tools/test_installation.py`? You wrote the command without the `3`.

Best,
Johannes

**Comment by jniediek** [comment]
I would like to know where in your file system you have the `dist-packages` folder.  One option to find this folder is to run

`python3 -m site` 

in the command line. In my case, this gives

```
sys.path = [
    '/home/johannes/Repositories/combinato',
    '/usr/lib/python39.zip',
    '/usr/lib/python3.9',
    '/usr/lib/python3.9/lib-dynload',
    '/usr/local/lib/python3.9/dist-packages',
    '/usr/lib/python3/dist-packages',
]
```

So I have `combinato` explicitly in my `sys.path`. But I could also place `combinato` in `/usr/lib/python3/dist-packages` and it would still be found.

What's the situation at your site?

Besides this, I don't have any updates. It would be great if you could tell me which python distribution you use, and where you placed the combinato folder in your filesystem. Then I'll recreate the same situation and see if I understand the problem.

**Comment by lubavas** [comment]
Hi Johannes,

> have you also tried `python3 tools/test_installation.py`? You wrote the command without the `3`.

Yes, I tried and it retrieves just `Python` and that's it.

I also tried `python3 -m site` with the `3` and nothing happens there except `Python` string.

Best wishes,
Luba

**Comment by jniediek** [comment]
> When I try to import my own .ncs files and extract the spikes, it will find all files and directories, but it will still give another error:
> File "C:\Users\PauliY\Anaconda3\lib\site-packages\scipy\signal\filter_design.py", line 2366, in iirfilter
> raise ValueError("Digital filter critical frequencies ValueError: Digital filter critical frequencies must be 0 < Wn < 1
> 
> Does this error have anything to do with the previous 'solution'?

It's almost sure that there is no connection between this error and the `sys.path.append` that you did.

> If this doesn't have anything to do with the previous problem I can open another Issue about this.

Yes, that would be great!

**Comment by jniediek** [comment]
> > have you also tried `python3 tools/test_installation.py`? You wrote the command without the `3`.
> 
> Yes, I tried and it retrieves just `Python` and that's it.
> 
> I also tried `python3 -m site` with the `3` and nothing happens there except `Python` string.
> 

Hi,

I'm having trouble understanding what sort of system you're using. If you tell me what python distribution (anaconda or something else?) you use and where in your system you placed combinato, I'll try to recreate the situation on my own computer to understand the problem.

**Comment by lubavas** [comment]
> > > have you also tried `python3 tools/test_installation.py`? You wrote the command without the `3`.
> > 
> > 
> > Yes, I tried and it retrieves just `Python` and that's it.
> > I also tried `python3 -m site` with the `3` and nothing happens there except `Python` string.
> 
> I'm having trouble understanding what sort of system you're using. If you tell me what python distribution (anaconda or something else?) you use and where in your system you placed combinato, I'll try to recreate the situation on my own computer to understand the problem.

Hi Johannes,

Thank you for the answer! Sure! I use a Win 10 Pro system and have 64-bit Anaconda3 installed (I used default installation path for it if this matters). I cloned combinato into `C:\codes` folder on my computer and Windows and Anaconda are stored on the same disk.

Best wishes,
Luba

**Comment by lubavas** [comment]
Hi Yves  @YvesPauli ,

Thanks a lot for your suggestion! I tried to run `sys.path.append('C:/users/your/combinato-master/location')` that you proposed in my case and re-ran the installation. My shell returned the following after `python tools/test_installation.py`  (@jniediek this may be informative for you)

`Found Combinato`
`SPC binary not found or not executable: [WinError 87] Параметр задан неверно`
`Place SPC binary in a folder and set path in options.py`
`Re-run after fixing problems.`
`'montage' from ImageMagick not found: [WinError 2] Не удается найти указанный файл`
`Plotting continuous data will not work`

At least it found combinato this time though still misses SPC.

Best wishes,
Luba

**Comment by YvesPauli** [comment]
@lubavas try rerunning the setup_options.py file.
maybe you have an old path to the SPC binary. I had the same problem and fixed it that way.
Best,
Yves

**Comment by lubavas** [comment]
Hi Yves @YvesPauli ,

> @lubavas try rerunning the setup_options.py file.
> maybe you have an old path to the SPC binary. I had the same problem and fixed it that way.
> Best,
> Yves
> edit: of course delete the previously created options.py file first.

Thank you for your suggestions! Now the code returned the following:

`Found Combinato`
`Found SPC binary`
`Your version of pytables is 3.6.1`
`Combinato clustering setup: no problems detected.`
`'montage' from ImageMagick not found: [WinError 2] Не удается найти указанный файл`
`Plotting continuous data will not work`

This seems like the installation worked well. :)

**Comment by jniediek** [comment]
Great! I close the issue.
