### ISSUE TITLE
css-extract --matfile issue

### ISSUE THREAD

**Issue by loublanpain** [jniediek/combinato#52]
Hello,

I have been trying to use the ```css-extract``` command on a mat file (i.e. with the option ```--matfile```), which was produced from a Blackrock NS6 file (1 mat file for recording from 1 channel). Although the command has worked in the past in our hands, it recently did not work for one of my mat files: the program stays stuck after reading the file- cf screenshot below.
![image](https://user-images.githubusercontent.com/43485885/109865947-b31a8200-7c32-11eb-987e-86b9305e5169.png)

I have noticed that the command does work on the file, if I reduce the size of the file- i.e. for instance, I remove half of the data from this recording. I am thus assuming this issue might be due to my original file being too large- ~250MB. Does that sound right? Have people encountered this issue before?

Thank you!

Lou

**Comment by jniediek** [comment]
Hi Lou,

Unfortunately the matfile support is indeed not that great. People have encountered a similar situation before. One way to go around the problem is to convert the data to the h5 format in matlab, for example by [using the `'-v7.3'` option of the save command]( https://www.mathworks.com/help/matlab/ref/save.html#btox10b-1-version). 

Then, you can use `css-extract --h5` on the data, which should suffer a lot less from getting stuck.

**Comment by loublanpain** [comment]
Hi Johannes,

Thank you for your prompt reply. So my understanding is that I should still convert Blackrock NS6 format to .mat format (1 .mat file for each channel), but using the ```'-v.3'``` option. I would then apply ```css-extract``` on the .mat file, using the ```--h5``` option. I have tried a few alternations with that option but no success so far. What would the whole line of code look like? In the past, I have used additional options and so my line looked like this:
```css-extract --matfile $filename --matfile-scale-factor 0.25```

**Comment by jniediek** [comment]
Hi Lou,

I understood now that the `save` command of Matlab does not allow to create 1-dimensional arrays, everything has (at least) 2 dimensions. But `css-extract` expects the data to come as a 1-dimensional array.

So what I tested is the following.
In Matlab:

```
data = your_blackrock_data;
h5create('test.h5', '/data', length(data))
h5write('test.h5', '/data', data)
```
On the command line:

```
css-extract --h5 --files test.h5
```

This worked for me. If you need to rescale your data by a factor of 0.25, you can do it before you save it to the `h5` file.

If you need to specify the sampling rate, you can save it as a variable `sr` in the `h5` file.

**Comment by loublanpain** [comment]
Hi Johannes,

That works- thank you so much for helping me out with this issue!

Lou
