### ISSUE TITLE
Unable to load Combinato

### ISSUE THREAD

**Issue by sukru-okk** [jniediek/combinato#54]
Hi,
Please find the error explanation when i tried to install combinato. Actually same error messages was discussed under the title "combinato installation on Windows #51" but I tried all suggestions even by YvesPauli and still i have same error

```
(base) PS C:\Users\SUKRU\Anaconda3\Lib\site-packages\combinato-master> python tools/test_installation.py
Unable to load Combinato: No module named 'combinato'
Check your PYTHONPATH and make sure to copy
combinato/default_options.py to combinato/options.py
Re-run after fixing problems.
'montage' from ImageMagick not found: [WinError 2] The system cannot find the file specified
Plotting continuous data will not work
(base) PS C:\Users\SUKRU\Anaconda3\Lib\site-packages\combinato-master>
```
In my computer, there is Win10 and standard Anaconda

**Comment by jniediek** [comment]
Hi, could you explain exactly which steps from the explanation in #51 you repeated?
Thank you
Johannes

**Comment by sukru-okk** [comment]
Many thanks for your quick reply.
Actually I tried all of them, first of all I opened the 'options.py' with notepad++ and checked that all lines were the same with 'default_options.py'. All are the same except line 18 (CLUS BINARY) and it is normal right?
then
I added both '.../combinato-master\combinato' and '....combinato-master' to the path of the system.
Then 
I tried to follow the suggestions of YvesPauli. He offered 'appending the path in the python code in the test_installation file.' But it also does not work.
and finally, i checked my site using 'python -m site' as you suggest and here is the result:
```
sys.path = [
    'C:\\Users\\SUKRU\\Anaconda3\\Lib\\site-packages\\combinato-master',
    'C:\\Users\\SUKRU\\Anaconda3\\python37.zip',
    'C:\\Users\\SUKRU\\Anaconda3\\DLLs',
    'C:\\Users\\SUKRU\\Anaconda3\\lib',
    'C:\\Users\\SUKRU\\Anaconda3',
    'C:\\Users\\SUKRU\\Anaconda3\\lib\\site-packages',
    'C:\\Users\\SUKRU\\Anaconda3\\lib\\site-packages\\win32',
    'C:\\Users\\SUKRU\\Anaconda3\\lib\\site-packages\\win32\\lib',
    'C:\\Users\\SUKRU\\Anaconda3\\lib\\site-packages\\Pythonwin',
]```

**Comment by jniediek** [comment]
This is quite strange. What happens if you start the python interpreter and directly type 
```from combinato import Combinato```?

**Comment by sukru-okk** [comment]
Thanks for your interest. Please see the following photo of the Anaconda shell
<img width="592" alt="Screenshot 2021-05-31 210646" src="https://user-images.githubusercontent.com/84911035/120232591-26448c00-c254-11eb-896d-7e62f55a1451.png">

**Comment by jniediek** [comment]
Hi!
So let's check that you can load Combinato (in this case with capital C) when you move to the containing folder. Could you move to the folder `C:\Users\SUKRU\Anaconda3\Lib\site-packages\combinato-master` and repeat the 
```from combinato import Combinato``` there?

**Comment by sukru-okk** [comment]
As you said, i moved to the folder  `C:\Users\SUKRU\Anaconda3\Lib\site-packages\combinato-master` and repeated the `from combinato import Combinato` there .
![image](https://user-images.githubusercontent.com/84911035/120324327-cd720380-c2e6-11eb-8ddc-83234f5ad4b9.png)

As you can see it has a error regarding back-slash (\) so I changed them into slash (/) in the options.py as following
```
CLUS_BINARY = 'C:/Users/SUKRU/Anaconda3/Lib/site-packages/combinato-master/spc/cluster_64.exe' 
```
Now  `from combinato import Combinato` works. BUT the `python tools/test_installation.py` still doesn't work. please see the following figure
![image](https://user-images.githubusercontent.com/84911035/120326304-e085d300-c2e8-11eb-939f-f7223addb8c5.png)

**Comment by mselmanyildirim** [comment]
I have a similar issue, I think. I  use miniconda on windows 7 pc.
I extracted the repository to an arbitrary convenient folder:
`D:\someArbitraryFolder\combinato-master`

Then, using Anaconda PowerShell Prompt, moved to repository folder.
Successfully run:
```
python setup_options.py
Found and executed SPC binary D:\someArbitraryFolder\combinato-master\spc\cluster_64.exe
```
Immediately tried following with no success:
```
python tools/test_installation.py
Unable to load Combinato: No module named 'combinato'
Check your PYTHONPATH and make sure to copy
combinato/default_options.py to combinato/options.py
Re-run after fixing problems.
'montage' from ImageMagick not found: [WinError 2] Sistem belirtilen dosyayı bulamıyor
Plotting continuous data will not work
```

Your suggestion `from combinato import Combinato`, worked, by the way.

**Comment by mselmanyildirim** [comment]
To add inner combinato folder to the path of current session, I run following powershell script:
```
$env:Path += ";D:\someArbitraryFolder\combinato-master\combinato"
```
but it didn't help with `python tools/test_installation.py`

Also I tried to prepend the combinato-master to path via  
`$env:Path = "D:\someArbitraryFolder\combinato-master;" + $env:Path`
to no avail. I mean, path is added, but `test_installation.py` doesn't work.

Does this have anything to do with the fact that Anaconda isolates python and packages? I already use Anaconda powershell prompt, though.

**Comment by mselmanyildirim** [comment]
```
python
>>>import sys
>>>sys.path
```
doesn't contain combinato, but
```
python -m site
```
DOES contain location of combinato-master at the first item.

**Comment by jniediek** [comment]
Hi!
The information supplied by @mselmanyildirim shows that (at least with miniconda) there is a discrepancy between the `sys.path` and `python -m site`. 

For now, could you move the inner combinato folder to one of the places contained in `sys.path`? There it will be found.

Based on the reports about difficulties installing combinato on Windows, I'll create a pip package for it as soon as I can.



> ```
> python
> >>>import sys
> >>>sys.path
> ```
> 
> doesn't contain combinato, but
> 
> ```
> python -m site
> ```
> 
> DOES contain location of combinato-master at the first item.

**Comment by jniediek** [comment]
Another comment, mostly relevant for @sukru-okk. In https://github.com/jniediek/combinato/issues/54#issuecomment-850397616 you show that `combinato-master` is located in `C:\\Users\\SUKRU\\Anaconda3\\Lib\\site-packages\`. But what should actually be located there is the "inner" `combinato` folder. So try moving the folder `combinato` that's currently inside `combinato-master` to the location `C:\\Users\\SUKRU\\Anaconda3\\Lib\\site-packages\`.

**Comment by jniediek** [comment]
And yet another comment for @mselmanyildirim : You can try to move the inner `combinato` folder to the directory `miniconda3/pkgs`, with `miniconda3` the location of your miniconda installation.

**Comment by sukru-okk** [comment]
Hi,
Thanks for all comments and suggestions.
What I did: 
I copied "inner" `combinato` folder and pasted into `... \site-packages`. Then I tried to run `python setup_options.py` but of course it didnt. So I copied not just `setup_options.py` but all files in the `combinato-master` folder to the "inner" `combinato` folder which is located in `...\site-packages`. And tried again. Please look at the following screenshot.

![image](https://user-images.githubusercontent.com/84911035/120532256-ca0e7300-c3df-11eb-81a9-2f65ab8ee873.png)

it says "Combinato clustering setup: no problems detected.", 
Is it OK, what do you think now? I mean, could we solve the exact root of the problem or not?
Would this solution be cause other problems while running the combinato?

**Comment by jniediek** [comment]
Hi,
if it works it works. Have you tried to run the tutorials and to actually work with data?

**Comment by mselmanyildirim** [comment]
I copied inner combinato folder into `...Miniconda3\Lib\site-packages\`. Inside it, in the `options.py` , I fixed the `CLUS_BINARY` directory. 
It was like `...combinato-master\spc\cluster_64.exe'` and I changed it like `...combinato-master\\spc\\cluster_64.exe'`. Now it finds combinato and spc binary. 
Thank you for responses. 

Just to inform: Copying `combinato` into `miniconda3/pkgs` didn't work. 
`miniconda3/pkgs`  doesn't seem to be on `sys.path`

**Comment by sukru-okk** [comment]
Hi,
i just finished Tutorial Part I without any problem. As you recognized and said "a pip package" for windows would be cool. 
 If I have a problem because of any reason, I think I should ask under a different "issue title", right?

Many Thanks Again

**Comment by jniediek** [comment]
@sukru-okk Cool! Yes, please feel free to start a new Issue for any new problem.
