### ISSUE TITLE
Issue running 'python setup_options.py'

### ISSUE THREAD

**Issue by Elliott365** [jniediek/combinato#55]
Hello I am using a 16-inch MacBook Pro 2019 with an Intel 2.6 GHz 6-Core Intel Core i7 processor. When running the 'python setup_options.py' command when in the Combinato shell I obtain the following error:

[Errno 86] Bad CPU type in executable: '/Users/nicholas.tastet/Applications/anaconda3/lib/python3.8/site-packages/combinato/spc/cluster_maci.exe'

I have attempted to route to another executable to see if that was the issue but that also resulted in a failure

Does anyone know how I can edit the executable file in question on MacOS so that I can resolve the issue?

**Comment by jniediek** [comment]
Hi,
have you tried the "cluster_mac_new" binary?

**Comment by Elliott365** [comment]
I have, I get this error
[Errno 13] Permission denied

**Comment by jniediek** [comment]
Apparently there is an issue with file permissions then. Try to run
`chmod 755 cluster_mac_new.exe`.

I also changed the permissions in the most recent version available here on github, you can also try to pull/re-download combinato.

Note that the previous `master` branch is now called `main`.

**Comment by Elliott365** [comment]
thank you so much for the help! Ive managed to get it working! I'm currently responsible for figuring out spike sorting/clustering for our lab and my PI is asking for computer specifications for a dedicated PC for it in the lab. May I ask what computer specs you generally use for the data you collect?

**Comment by jniediek** [comment]
Hi! I can only say that the hardware specifications don't matter very much here. The speed of the spike sorting itself mostly depends on the numbers of cores your CPU has. There are many computers available with 8 cores now, and some with even more. It also helps to have the data stored on a fast disk. I think 1TB SSDs are affordable nowadays.

But please consider that already back in 2014 we were able to run, within a few hours, the spike sorting of a full-night recording with 96 channels. A standard computer from 2021 is much, much faster than the computers we used back in 2014!

Feel free to ask more specific questions if you like.

**Comment by Elliott365** [comment]
Thank you very much! I really appreciate it. Is there any reason to invest in a GPU for the purposes of spike sorting? I know that some spike sorting programs require one but I can't figure out what the performance value of having a medium/higher end one is. I imagine it won't make a difference in the algorithm run time but could affect how responsive the GUI is. 

We have appreciated your work on the software by the way! No one in our lab has a computer science or mathematics background so Combinato is a big stepping point for us into more computational/data science work around neurobiology.

**Comment by jniediek** [comment]
Thank you for the feedback! For Combinato the quality of the GPU is not relevant. The GUI of Combinato is simple enough even for low-end GPUs to handle.
