### ISSUE TITLE
Header-reading function ncs_info not compatible with Pegasus 2.1.1 header syntax (suggested fix)

### ISSUE THREAD

**Issue by adriangutierrezg** [jniediek/combinato#57]
Hi Johannes,

I realized that the current ncs_info() function for reading the header of NCS files (in nlxio) is not compatible with the Pegasus' 2.1.1 Opening/Closing date and time syntax. I think this is partially because it expects this information to be in a 7-item-long string list in this line: 

https://github.com/jniediek/combinato/blob/ee6fe8fcc5748da758add38ee842ce942151a4bb/combinato/basics/nlxio.py#L133

I guess this has to do with how Cheetah headers look like (since it works well when dealing with them), but the NCS files generated with Pegasus 2.1.1 have header entries that look like this: 

 '-TimeCreated yyyy/mm/dd HH:MM:SS'
 '-TimeClosed yyyy/mm/dd HH:MM:SS'

which results in a 3-long-item list. (I currently have solved the issue by pre-modifying the Pegasus file's header to look like a Cheetah file):

'## Time Opened (m/d/y): m/dd/yyyy  (h: m:s.ms) hh:MM:ss.f'
'## Time Closed (m/d/y): m/dd/yyyy  (h: m:s.ms) hh:MM:ss.f'

Is this header information called again within combinato/important for clustering? 

In any case, I could suggest a quick-and-dirty fix somewhat like this (starting from line 123 in nlxio): 

        if len(field) == 2:
            try:
                field[1] = int(field[1])
            except ValueError:
                try:
                    field[1] = float(field[1])
                except ValueError:
                    pass
            d[field[0][1:]] = field[1]
         
        ### fix start
        #Dealing with Pegasus Opened/Closed date&time strings
        elif len(field) == 3:
            if field[0] in ('-TimeCreated', '-TimeClosed'):
                pddate = datetime.strptime(field[1] + ' ' + field[2], '%Y/%m/%d %H:%M:%S')
                dt = datetime(pddate.year, pddate.month, pddate.day, pddate.hour, \
                                       pddate.minute, pddate.second)
                d[field[0][1:]] = dt
        ### fix end

        elif len(field) == 7:
            if field[0] == '##':
                if field[2] in ('Opened', 'Closed'):
                    timeg = TIME_PATTERN.match(field[6]).groups()
                    pdt = datetime.strptime(
                        field[4] + ' ' + timeg[0],
                        '%m/%d/%Y %H:%M:%S')
                    dt = datetime(pdt.year,
                                  pdt.month,
                                  pdt.day,
                                  pdt.hour,
                                  pdt.minute,
                                  pdt.second,
                                  int(timeg[1])*1000)
                d[field[2].lower()] = dt
    if 'AcqEntName' not in d:
        d[u'AcqEntName'] = 'channel' + str(d['ADChannel'])
    return d

One could also get fancy and make sure to homogenize key values in the dictionary for completion. I haven't tested this yet with my own clone, but I have done something similar with some of the stuff I've written for reading both Cheetah and Pegasus header info.  

Cheers!
Adrian.

**Comment by jniediek** [comment]
Hi Adrian,

Thanks for the fix, it looks good to me! The idea of changing raw data on disk as a workaround seems a bit strange to me, so let's fix the issue in Combinato. 

Would you mind to create a pull request?

As to homogenizing the dict keys, I can only tell you that Combinato uses the `opened` and `closed` fields of the ncs header only in two of the legacy scripts in the `tools` folder. I'm totally fine with leaving these tools in their current state and fixing the dict keys only when that's really needed.

Best,
Johannes

**Comment by adriangutierrezg** [comment]
Dear Johannes,

As suggested, I have opened a pull request on this issue. 

(Just for clarification, I have so far only added information to the headers of the files, not modifying any of its original content :) - but that's a different discussion)

Cheers and thanks!
Adrian.

**Comment by jniediek** [comment]
Wonderful, thank you!
Johannes
