### ISSUE TITLE
no plots in `overview` folder

### ISSUE THREAD

**Issue by marcoistasy** [jniediek/combinato#60]
Hello!

I am working through the Combinato [Tutorial 1](https://github.com/jniediek/combinato/wiki/Tutorial-Synthetic-Data) but am noticing behaviour that deviates from what is documented.  When I run `css-plot-sorted --label sort_pos_simple`, the intended behaviour is that an `overview` directory is created which has a single plot -- however, the overview directory which is created for me is empty.

Is this by any chance related to Issue #38, and would you be able to advise on how to fix it?

**Comment by jniediek** [comment]
Hello,
do you see any error messages? Do you manage to produce output by specifying a specific file via the `--files` option of `css-plot-sorted`

**Comment by marcoistasy** [comment]
hey @jniediek! So I somehow managed to make it work if I run `css-plot-sorted --label sort_pos_simple` _outside_ the `simulation_5` directory. Is this expected behaviour? If so, what would the reaction be when running `css-plot-sorted --label sort_pos_simple` in a parent directory holding multiple clustering directories (i.e those created when running `css-extract`)?

**Comment by marcoistasy** [comment]
also @jniediek, no plots are being generated when running `css-plot-rawsignal` as well. I am following [Tutorial #3](https://github.com/jniediek/combinato/wiki/Tutorial-Real-Data) -- however, in this case, no `overview` directory is created in the first place.

**Comment by jniediek** [comment]
> hey @jniediek! So I somehow managed to make it work if I run `css-plot-sorted --label sort_pos_simple` _outside_ the `simulation_5` directory. Is this expected behaviour? If so, what would the reaction be when running `css-plot-sorted --label sort_pos_simple` in a parent directory holding multiple clustering directories (i.e those created when running `css-extract`)?

Hey @marcoistasy, happy to hear that somehow it worked for you. Your question makes sense, the behavior of `css-plot-sorted` is probably not very intuitive. Basically, there are two ways to run it, either only with the `--label` option in which case it looks for all channel folders to run on (in your case, only the `simulation_5` folder), or with the `--files` option (on top of `--label`) in which case you explicitly specify which files it should run and plot. I mostly use the `--label` option without `--files` after clustering many channels, to plot all of them in the end.

**Comment by jniediek** [comment]
> also @jniediek, no plots are being generated when running `css-plot-rawsignal` as well. I am following [Tutorial #3](https://github.com/jniediek/combinato/wiki/Tutorial-Real-Data) -- however, in this case, no `overview` directory is created in the first place.

Hey again, the `css-plot-rawsignal` script currently invokes the program [`montage`](https://imagemagick.org/script/montage.php), maybe you don't have it? On Windows, you might even have to change the path to `montage` [here](https://github.com/jniediek/combinato/blob/b9aae32cdd0a0b2a4257d718dfca323a58f4bff9/combinato/plot/plot_rawsignal.py#L165).

**Comment by marcoistasy** [comment]
@jniediek so I didn't have `montage` installed -- however, even after installing using `sudo apt install imagemagick` no `overview` folder is being created. Here is the output from the terminal in which you can see that I ran `css-plot-rawsignal` both in the directory containing the `data.h5` file as well as the parent directory. 

```
(visification) ➜  LAINSu1_0019 ls
data_LAINSu1_0019.h5  log.txt  sort_pos_simple  sort_pos_simple_0000000_0002690
(visification) ➜  LAINSu1_0019 css-plot-rawsignal
Plotting took 0 seconds
(visification) ➜  LAINSu1_0019 ls
data_LAINSu1_0019.h5  log.txt  sort_pos_simple  sort_pos_simple_0000000_0002690
(visification) ➜  LAINSu1_0019 cd ..
(visification) ➜  combinato_sorting_output ls
LAINSu1_0019  LAINSu7_0019  LASTGu5_0019  LMINSu3_0019  LMTu1_0019  LMTu7_0019    LPINSu5_0019  LPTTu3_0019
LAINSu2_0019  LAINSu8_0019  LASTGu6_0019  LMINSu4_0019  LMTu2_0019  LMTu8_0019    LPINSu6_0019  LPTTu4_0019
LAINSu3_0019  LASTGu1_0019  LASTGu7_0019  LMINSu5_0019  LMTu3_0019  LPINSu1_0019  LPINSu7_0019  LPTTu5_0019
LAINSu4_0019  LASTGu2_0019  LASTGu8_0019  LMINSu6_0019  LMTu4_0019  LPINSu2_0019  LPINSu8_0019  LPTTu6_0019
LAINSu5_0019  LASTGu3_0019  LMINSu1_0019  LMINSu7_0019  LMTu5_0019  LPINSu3_0019  LPTTu1_0019   LPTTu7_0019
LAINSu6_0019  LASTGu4_0019  LMINSu2_0019  LMINSu8_0019  LMTu6_0019  LPINSu4_0019  LPTTu2_0019   LPTTu8_0019
(visification) ➜  combinato_sorting_output css-plot-rawsignal
Plotting took 0 seconds
(visification) ➜  combinato_sorting_output
```

**Comment by marcoistasy** [comment]
@jniediek i also tried running `css-plot-rawsignal` in the directory containing the actual `.ncs` files but nothing happened.

**Comment by jniediek** [comment]
I see. I think the reason is that your `.ncs` filenames don't start with `CSC`. 

Try this in python:

```
>>> from combinato.util.tools import get_regions
>>> get_regions('.')
defaultdict(<class 'list'>, {'LMH': ['./CSC25.ncs', './CSC26.ncs', './CSC27.ncs',
 './CSC28.ncs', './CSC29.ncs', './CSC30.ncs', './CSC31.ncs', './CSC32.ncs'],
 'LA': ['./CSC1.ncs', './CSC2.ncs', '
```
I would guess that in your case the lists of `.ncs` files will be empty. To change it, you have to edit this line:

https://github.com/jniediek/combinato/blob/b9aae32cdd0a0b2a4257d718dfca323a58f4bff9/combinato/util/tools.py#L111

**Comment by cpdavis** [comment]
Hi @jniediek, thanks for all you do here. I am having a similar issue with no plots showing up in the overview folder, except it is also accompanied by the following error message. For context, I am running on Mac OS 12.0.1. Everything up to this point seems to have worked without issue. It doesn't seem to matter whether I run `css-plot-sorted --label sort_pos_simple` within or outside of the `simulation_5` directory.

> Ncs file not found, no header!
Traceback (most recent call last):
  File "/Users/charles/opt/anaconda3/bin/css-plot-sorted", line 5, in <module>
    parse_args()
  File "/Users/charles/combinato/combinato/plot/plot_sorted.py", line 182, in parse_args
    run_file(fname, savefolder, sign, label)
  File "/Users/charles/combinato/combinato/plot/plot_sorted.py", line 114, in run_file
    manager = Combinato(fname, sign, label)
  File "/Users/charles/combinato/combinato/manager/manager_cat.py", line 440, in __init__
    res = self.init_sorting(sorting_session)
  File "/Users/charles/combinato/combinato/manager/manager_cat.py", line 213, in init_sorting
    self.sorting = SortingFile(sorting_path)
  File "/Users/charles/combinato/combinato/manager/manager_cat.py", line 30, in __init__
    self.sign = str(temp, 'utf-8')
TypeError: decoding str is not supported
Closing remaining open files:/Users/charles/Desktop/simulation_5/sort_pos_simple/sort_cat.h5...done/Users/charles/Desktop/simulation_5/data_simulation_5.h5...done

**Comment by jniediek** [comment]
Hi @cpdavis, the problem you reported was most likely related to a datatype problem in the `.h5` files. Could you try the most recent version of combinato to see if the error is resolved?

**Comment by jniediek** [comment]
> > hey @jniediek! So I somehow managed to make it work if I run `css-plot-sorted --label sort_pos_simple` _outside_ the `simulation_5` directory. Is this expected behaviour? If so, what would the reaction be when running `css-plot-sorted --label sort_pos_simple` in a parent directory holding multiple clustering directories (i.e those created when running `css-extract`)?
> 
> Hey @marcoistasy, happy to hear that somehow it worked for you. Your question makes sense, the behavior of `css-plot-sorted` is probably not very intuitive. Basically, there are two ways to run it, either only with the `--label` option in which case it looks for all channel folders to run on (in your case, only the `simulation_5` folder), or with the `--files` option (on top of `--label`) in which case you explicitly specify which files it should run and plot. I mostly use the `--label` option without `--files` after clustering many channels, to plot all of them in the end.

Hi @cpdavis, just to catch up with you, could you write the exact command you're using and in which folder you run it? Thank you.

**Comment by cpdavis** [comment]
Hi @jniediek so sorry to have continued the discussion before exhausting everything. I ran `git fetch` in my local combinato repository but didn't confirm that the right scripts had updated - `git pull` did the trick and now it's working. Thanks again for bearing with me.
