### ISSUE TITLE
Tutorial data is no longer available

### ISSUE THREAD

**Issue by TomDonoghue** [jniediek/combinato#61]
The real data that is linked in the ["Tutorial Real Data" ](https://github.com/jniediek/combinato/wiki/Tutorial-Real-Data) no longer seems to be available. 

When I follow the link, I get the following:
![Screen Shot 2021-11-13 at 1 24 18 PM](https://user-images.githubusercontent.com/7727566/141655005-71dbbb44-f0e1-48b3-946e-b90f64ee2370.png)

**Comment by jniediek** [comment]
I'll replace the file ASAP.
Sorry for the inconvenience!

**Comment by jniediek** [comment]
There is a replacement file now. The screenshots in the tutorial don't match yet, will be updated.
