### ISSUE TITLE
TypeError when loading clustering results into the GUI

### ISSUE THREAD

**Issue by TomDonoghue** [jniediek/combinato#62]
I've been getting an error when trying to load into the GUI (after running `css-gui`) which launches okay. 

The error was:
`TypeError: decoding str is not supported`
Being raised from [here](https://github.com/jniediek/combinato/blob/main/combinato/manager/manager_cat.py#L30). 

I've traced the issue to this [commit](https://github.com/jniediek/combinato/commit/91cc42513e4fd29416d81133c82df77253926722#diff-a73deaddf0f55c89826f007e95f92bec07e13cf08bb7da03e0a85740d55b9d3b)

If I locally revert this commit, dropping the string typecasting, it then seems to work. 

For me, at least, the line seems to fail as the `temp` variable is a string (example: 'neg'), which then can't be decoded, and so the TypeError is thrown. It seems it's expected that `temp` would be a bytes object, but this seems to not be guaranteed. 

I don't know enough about the context here to know why `temp` ends up the type it does, but I think it might be useful to revert and/or tweak the above commit - one potentially easy fix is to type check `temp` before attempting to decode it.

**Comment by jniediek** [comment]
Dear @TomDonoghue,
Thank you very much for the clear description and tracing of the error. The `temp` variable originates from an HDF5 file, and whether it's a byte object or a string depends on what version of Python was used to create this HDF5 file. Your idea of checking the type of `temp` first is excellent I think, would you like to greate a pull request?  

Also see [here](https://github.com/jniediek/combinato/commit/91cc42513e4fd29416d81133c82df77253926722#r60560240)

**Comment by TomDonoghue** [comment]
Hey @jniediek - sorry for not following up on this, I've been travelling recently, and didn't get a chance to follow up. The fix looks good to me, thanks!
