### ISSUE TITLE
Broken link in Tutorial Data Part I

### ISSUE THREAD

**Issue by MariosPanayi** [jniediek/combinato#63]
Hi there, I think the link for the synthetic data for step 1 in Tutorial Part I [https://github.com/jniediek/combinato/wiki/Tutorial-Synthetic-Data] is no longer working.
i.e. this link http://bioweb.me/CPGJNM2012-dataset/simulation_5.mat
Is there another link to these data?
Thanks :)
Marios

**Comment by jniediek** [comment]
Thanks for pointing this out! I updated the link, see here https://github.com/jniediek/combinato/wiki/Tutorial-Synthetic-Data#1-download-sample-data
