### ISSUE TITLE
Unable to Install on Mac, bad CPU type

### ISSUE THREAD

**Issue by x-avent** [jniediek/combinato#73]
Hi Johannes,
I try to install combinato on my mac (macOS Monterey; MacBook Pro, 16-inch; Intel Core i7; 32 GB).

However, when running 
> python setup-options.py 
I get the following error:

> Could not execute SPC binary ~/anaconda3/lib/python3.9/site-packages/combinato-main/spc/cluster_maci.exe
> [Errno 86] Bad CPU type in executable: ~/anaconda3/lib/python3.9/site-packages/combinato-main/spc/cluster_maci.exe'

From the apple support I understood that this may have to do with an incompatible default shell. Mine is -zsh so I tried changing it to -bash or -sh. Same error, unfortunately.

Do you have any idea on how to solve that problem? Any help is very much appreciated. Thank you!

**Comment by jniediek** [comment]
Hi x-avent, my first guess would be that `cluster_maci.exe` is not the correct executable for your CPU. Could you specify the model name/number of your mac? I'll figure out which executable you need on that machine.

**Comment by x-avent** [comment]
Hi,
here more information about my mac:

MacBookPro16,1
  Processor Name:	6-Core Intel Core i7 (I7-9750H)
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB

Does that help?
Thank you

**Comment by jniediek** [comment]
Hi, sorry for the late reply. Could you try the following: in the script `setup_options.py` that you were running, line 27 sets the binary for you platform. If you change the `cluster_maci.exe` to `cluster_mac_new.exe`, does the setup work?

**Comment by x-avent** [comment]
Hi, it seems to have worked now! Thank you!
